### ISSUE TITLE
"Continue" included in autogenerated custom rules

### ISSUE THREAD

**Issue by gac21116** [vincentsels/poe2filter#2]
The result is that, for example, if you choose to have jewelry hidden as a default state for all jewelry but then create a custom rule for, say, a heavy belt - the belt will ultimately be hidden. 

On a related note - because the default color formatting for currency orbs is not removed when creating a custom rule,  no custom coloring is applied because it will always end up defaulting to the original coloring in the "basic currency" section of the file due to the above

It is helpful for certain items, such as top-tier currency to include continue in the autogenerated rule (so that you can have your custom rule applied, as well as the top-tier currency sound+text formatting) but it is an issue for use-cases such as the original belt use-case mentioned as well as an issue when someone wants a different custom coloring for currency orbs than the default color formatting

Custom rule auto-generated as follows:

Show
   Class == "Belts"
   BaseType == "Heavy Belt"
   Rarity >= "Normal"
   PlayEffect Brown
   MinimapIcon 2 Brown Pentagon
   Continue

**Comment by vincentsels** [comment]
Yea I know, you typically won't want to use 'Continue', or be careful when you do. I thought of warning about that more clearly, irconically enough exactly this case, but it's a trade-off with taking up more space... I'll include the warning after all :).

**Comment by vincentsels** [comment]
Actually, this Continue statement pretty much only makes sense for additionnal cosmetic stuff, like changing the label or adding sound. There shouldn't really be any use cases where you need to use it otherwise; you should be able to achieve anything just using the order of rules. I'll remove it until I add 'custom label & sound options'.

**Comment by vincentsels** [comment]
In your case what you probably want to do is this;

![image](https://github.com/user-attachments/assets/6a2ea324-457c-4226-bd6d-fd589ac02f09)

```Show
  Class == "Belts"
  BaseType == "Heavy Belt"
  Rarity <= "Magic"
  PlayEffect Brown
  MinimapIcon 2 Brown Pentagon```

Since any rare or unique jewellery including belts will always be shown anyway. The rare ones will then not be highlighted as brown though, but as default yellow.

Actually, I should probably do an overhaul of the 'Hide' quick filters, like 'Hide Jewellery', where I allow the user to list exceptions.

**Comment by vincentsels** [comment]
Removed the 'continue' option for now to prevent further confusion.

**Comment by gac21116** [comment]
> Actually, this Continue statement pretty much only makes sense for additionnal cosmetic stuff, like changing the label or adding sound. There shouldn't really be any use cases where you need to use it otherwise; you should be able to achieve anything just using the order of rules. I'll remove it until I add 'custom label & sound options'.

yeah I think this is correct - most useful for being able to customize coloring as well as custom sound/text sizing for top-tier currency

I've been able to manually adjust the file to suit my needs but wasn't sure how you wanted to handle it for a broader audience within the tool itself. Thanks for the quick responses/action
